name: "install-robotpy-build"
description: "Installs robotpy-build"
inputs:
  python:
    description: "python executable"
    required: false
    default: python
runs:
  using: "node16"
  main: dist/index.js
