name: check-for-maven-update
description: "Check for new version of libraries on maven"
inputs:
  token:
    description: "github token"
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'