name: "install-pure-build-deps"
description: "Install build dependencies"
inputs:
  python:
    description: "python executable"
    required: false
    default: python
  wheeldir:
    description: "Wheel directory"
    required: false
    default: linux_x86_64
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      ${{ inputs.python }} setup.py egg_info
      ${{ inputs.python }} -m pip install \
          --find-links https://www.tortall.net/~robotpy/wheels/2021/${{ inputs.wheeldir }} \
          wheel \
          $(grep -v '^\[' *.egg-info/requires.txt)
