name: "install-pure-build-deps"
description: "Install build dependencies"
inputs:
  python:
    description: "python executable"
    required: false
    default: python
runs:
  using: "composite"
  steps:
  - shell: bash
    run: |
      ${{ inputs.python }} setup.py egg_info
      ${{ inputs.python }} -m pip install \
          wheel \
          $(grep -v '^\[' *.egg-info/requires.txt)
